Buffed magic, resiliant, and basic blood frames
GTNewHorizons/MagicBees pull request #31
Opened 2023-08-27 01:26 UTC by hacatu

See [here](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14245).  Buffs the three most expensive frames (they are still worse than they were before the additive production change but that's the goal)

2023-08-27 18:46 UTC, Alastors commented
I mean the base blood one is meant to be terrible, it's supposed to sort of match the basic Magic frame, keep it consistent with that frame

2023-08-27 18:49 UTC, Alastors requested changes

2023-08-27 18:49 UTC, Alastors commented on src/main/java/magicbees/main/utils/compat/bloodmagic/ItemBloodBaseFrame.java
> +            return 3f; // buffed post additive production change
Nope, this is meant to stay 1, magic frame's production is 1. Keep them consistent.

If you're changing magic to 2, this should be 2.

2023-08-28 18:48 UTC, Alastors commented
Seems fine now, but I'd like @Runakai1's thoughts first since it's his baby

2023-09-13 06:53 UTC, Runakai1 approved these changes

2023-09-13 06:54 UTC, merged