Magic Apiary Texture Rework + Fix Research
GTNewHorizons/MagicBees pull request #32
Opened 2023-10-17 18:18 UTC by DrParadox7

Retextures Apiary GUI to the same style as Forestry's Bee Houses with enhanced clarity for icons:

Increased Production:
![image](https://github.com/GTNewHorizons/MagicBees/assets/47131096/877e42c0-e458-4afc-b73b-f0d646676c4d)
Decreased Lifespan:
![image](https://github.com/GTNewHorizons/MagicBees/assets/47131096/8c31ed7d-f01c-4702-a110-5a15c3f991bb)
Increased Mutation:
![image](https://github.com/GTNewHorizons/MagicBees/assets/47131096/01544fef-f2ab-4afb-a940-e260460337b7)

Also fixed Research langs not correctly localized.

2023-10-17 18:26 UTC, Alastors requested changes
Do not change the texture of the GUI

2023-10-17 18:26 UTC, Alastors commented on src/main/resources/assets/magicbees/textures/gui/apiary.png
No

2023-10-17 18:28 UTC, Alastors commented
The Magic Bees Apiary is a unique bit of thaumcraft, do not sully it by unifying textures when it is already so unique.

This PR as a whole is a reflection of someone who doesn't understand the vibrant uniqueness that each thaum addon brings to the table that is design.

Each texture, a kiss of specific style, a small impression of who the dev was, this is just sad.

2023-10-17 18:35 UTC, Dream-Master commented on src/main/resources/assets/magicbees/textures/gui/apiary.png
Maybe a mixture is nice. (gui saty icons changed) The new icons much cleaner expain where they stand for

2023-10-17 18:38 UTC, Alastors commented on src/main/resources/assets/magicbees/textures/gui/apiary.png
But if he wants to put a proper side by side, he's free to do so, no PR that changes icons should be passed if they don't even at the very least do that

2023-10-17 18:39 UTC, Dream-Master commented on src/main/resources/assets/magicbees/textures/gui/apiary.png
sure lets hear more people on this

2023-10-17 18:40 UTC, Alastors commented on src/main/resources/assets/magicbees/textures/gui/apiary.png
![apiary1](https://github.com/GTNewHorizons/MagicBees/assets/78517796/0fa39bcf-ec5f-4645-a6f4-96c0113b55ce)
besides are you telling me this

makes less sense than this:
![apiary2](https://github.com/GTNewHorizons/MagicBees/assets/78517796/490f49a7-2a9f-452f-82cd-9a230f66cd4b)

They're both downright nonsensical, so it literally doesn't matter.

2023-10-17 19:21 UTC, Prometheus0000 commented
I agree with alastor, there's no reason to change the icons. *Maybe* the background, but I don't really think that needs changing either. If the author wanted it to use 'Forestry's Bee House icons' (which I don't recall ever seeing BTW) they would have used them.

2023-10-17 19:28 UTC, Alastors commented
![apiary](https://github.com/GTNewHorizons/MagicBees/assets/78517796/a1eab5d8-29bd-4578-be48-3741f1652e9c)
I'd like to bring to focus one final thing as well, base forestry doesn't have icons, so these icons are entirely unique to the Magic Apiary

2023-10-17 22:43 UTC, SilearFlare commented
While you're at it, I'll pop in since the repo doesn't have any issues to actually start a discussion in and Alastor already did the same change between Gregapi and gregtech in https://github.com/GTNewHorizons/ThaumicHorizons/tree/gt6-gix, as mentioned in https://github.com/GTNewHorizons/ThaumicHorizons/issues/46, a specific commit in magic bees, specifically https://github.com/GTNewHorizons/MagicBees/commit/d9ef30fe32a71eb91bde9542c8fa52c4d2aa7ef1 crashes the modpack and using any version of magic bees alongside any version of gregtech outside of 5U causes a crash. 
At least in the case of thaumic horizons it was just a matter of enabling an external config which is disabled by default, in this case the mod just crashes with no option to do anything about it. and as it is, is impossible to play any version of magic bees past that commit.

Oh also the new icons are cool and I personally thing as an external observer that they should be changed :+1:

2023-10-17 23:28 UTC, bombcar commented on src/main/resources/assets/magicbees/textures/gui/apiary.png
Magic ain't technology no matter what some old sci-fi authors say. I say unique GUIs for the magical things is nice.

A gregtech style GUI should be for the beecompressor9000™ or some other technological disaster, not magic,

2023-10-17 23:57 UTC, DrParadox7 commented
These review are charming if not for their touch of creative flair.
MysteriousAges would appreciate a cleanup of Magic Bees' most cryptic aspect, especially after over a decade from its inception.

As a talented programmer artist yourself I get the apprehension, but when it comes to user interfaces, the ultimate aim should be making them feel cohesive and user-friendly which the original could use some improvement.

Anyways, you've asked for a comparison so here are the gifs (compression may slightly alter the colors).

**Old:**
![Magic Apiary Animation-old](https://github.com/GTNewHorizons/MagicBees/assets/47131096/b6528344-20f0-4165-af90-e29184ddad98)

**New:**
![Magic Apiary Animation-new](https://github.com/GTNewHorizons/MagicBees/assets/47131096/e305244a-8711-4bb0-a3bc-ac8cd697e302)

Things have been slightly tweaked in my latest iteration which is not included here but is available on request.

2023-10-18 00:03 UTC, Alastors commented
> MysteriousAges would appreciate a cleanup of Magic Bees' most cryptic aspect, especially after over a decade from its inception.
Who is MysteriousAges?

> As a talented programmer artist yourself I get the apprehension, but when it comes to user interfaces, the ultimate aim should be making them feel cohesive and user-friendly which the original could use some improvement.
Ehhhhhhhhhh, not so much with Thaumcraft, the majority of Thaumcraft consistently and intentionally keeps the UI user-unfriendly and enigmatic for various reasons, and it's important to stay consistent with that design goal, though this system is one of the less enigmatic given that the Thaumonomicon directly lists out what each of them mean. Though I hardly believe a full rework of the GUI itself is tantamount to making it any more "user friendly" you could make the argument for the icons sure, but personally, I don't think there is enough value here to justify the utter destruction of the original GUI in totality.

2023-10-18 00:06 UTC, Alastors commented
> > MysteriousAges would appreciate a cleanup of Magic Bees' most cryptic aspect, especially after over a decade from its inception.
> 
> ~Who is MysteriousAges?~ NVM you mean one of the devs, I fully invite him to come here and say the same then, though I would still disagree with that opinion personally. Of course that considered, he could just re-release the mod himself, given he still has ownership.
> 
> > As a talented programmer artist yourself I get the apprehension, but when it comes to user interfaces, the ultimate aim should be making them feel cohesive and user-friendly which the original could use some improvement.
> 
> Ehhhhhhhhhh, not so much with Thaumcraft, the majority of Thaumcraft consistently and intentionally keeps the UI user-unfriendly and enigmatic for various reasons, and it's important to stay consistent with that design goal, though this system is one of the less enigmatic given that the Thaumonomicon directly lists out what each of them mean. Though I hardly believe a full rework of the GUI itself is tantamount to making it any more "user friendly" you could make the argument for the icons sure, but personally, I don't think there is enough value here to justify the utter destruction of the original GUI in totality.
<img width="320" alt="Screen Shot 2023-10-17 at 8 06 04 PM" src="https://github.com/GTNewHorizons/MagicBees/assets/78517796/dfbbc232-2a08-4df6-ad62-2632f28e4ee3">

> MysteriousAges would appreciate a cleanup of Magic Bees' most cryptic aspect, especially after over a decade from its inception.

Given there's been no update to Magic Bees in over 3 years though, I hardly believe you speak for MysteriousAges.

2023-10-18 02:16 UTC, Connor-Colenso commented
Thanks for the rework, this second iteration looks much better imo.

2023-10-18 05:18 UTC, mitchej123 commented
I like the second iteration of the GUI. 


The icons seem slightly out of place for magic (at least the DNA one)

2023-10-18 11:28 UTC, Dream-Master commented
i like to see it with bees ingame. How the bees look like on nearly black backround?

2023-10-18 12:51 UTC, DrParadox7 commented
> i like to see it with bees ingame. How the bees look like on nearly black backround?
Sure, I can do that:
![in-use](https://github.com/GTNewHorizons/MagicBees/assets/47131096/d07b108d-c4ed-4986-8c6d-dee9a6122c69)

2023-10-18 12:53 UTC, Dream-Master commented
ok thanks for showing. I think the hexagons need to be more visible and also the slots.

2023-10-18 13:04 UTC, DrParadox7 commented
> The icons seem slightly out of place for magic (at least the DNA one)
I reluctantly agree with the sentiment. 
That DNA is definitely the weaker element of this design.

It is can be difficult to translate science elements such as genetic mutation into a magic theme.

I originally aimed to infuse a touch of alchemy, inspired by Fullmetal Alchemist/The Witcher 3 but I soon realized that this was quite a tough task, not just in the design-wise with a limited 10-pixel width canvas, but also in making sure it's easy to understand and use for everyone.

What you see is what I have settled on for lack of a better solution.

2023-10-19 18:16 UTC, Alastors commented
After hours of stringent and fervent debate, we have now updated our dev Code of Conduct, and thusly, I push forth that this PR breaks GTNH CoC 7-1 given how this proposal would shift the identity significantly too far away from the unique feel intended by magic within the pack, likewise, the alternative modification proposed in #meta-dev can be handled by GTNH CoC 7-4

7) Regarding textures within GTNH
   1) Regarding magic textures: within the vision of the modpack, magic is meant to feel, look, and be different than GregTech, any form of GUI update for the sake of (or that would inadvertently bring) consistency with GT GUIs should be rejected.
   2) n/a
   3) n/a
   4) Regarding inventory changing: GUIs that shift the colour of the player's internal inventory are allowed as long as its usage is consistent. Examples being: GT's Steam Machines, Magic Bee's Magic Apiary, Railcraft's Coke Oven, etc.

2023-10-19 23:07 UTC, DrParadox7 commented
> ok thanks for showing. I think the hexagons need to be more visible and also the slots.

I covered your valid concern. 
There were also a couple of other issues fixed with it:
- Moved "Inventory"  label a tad bit to the left.
- The GUI was getting cut at the bottom by 2 pixel (also affects the original)
![image](https://github.com/GTNewHorizons/MagicBees/assets/47131096/17925b3e-aaa9-416a-8c61-6f02aa37b60e)
This can be tested from here:
https://github.com/DrParadox7/MagicBees/releases/tag/2.7.1-LE

2023-10-19 23:08 UTC, DrParadox7 commented
@Alastors If you've already altered the rules to predetermine the outcome of this PR, there's no need for further opinions. 
Enforcing your authority to conclude this discussion should be just as easy.

2023-10-20 09:19 UTC, SilearFlare commented
Kinda defeats the whole point of having a discussion if ya can simply edit the rules to what can be done and can't be done mid-discussion, doesn't it? But then again I'm just here to point the issue with magic bees crashing with gt6 anyway :^)

2023-10-20 09:46 UTC, OneEyeMaker commented
@DrParadox7 What about recolor/tint light grey part of UI to make it more unique? (with color of Greatwood/Arcane stone/Thaumium)

2023-10-20 14:16 UTC, bombcar commented
This still looks like a GT machine to me - not really what I'd want, but I've not done bees or magic this far.

2023-10-20 14:19 UTC, Alastors commented
> Kinda defeats the whole point of having a discussion if ya can simply edit the rules to what can be done and can't be done mid-discussion, doesn't it? But then again I'm just here to point the issue with magic bees crashing with gt6 anyway :^)

The new ruling came after tireless debate for 2 days straight, that's literally the point of having rules, make rules when new issues come up.

2023-10-20 14:19 UTC, Alastors commented
> This still looks like a GT machine to me - not really what I'd want, but I've not done bees or magic this far.

This is the entire issue, it defaces Magic's identity for no real reason

2023-10-20 14:21 UTC, Alastors commented
> @DrParadox7 New UI looks nice. But what about to recolor/tint light grey part of new UI to make it more unique? (with color of Greatwood/Arcane stone/Thaumium)

There was also concern in those debates (not even mostly by me) that the icons look too "techy" compared to what the original looked like

2023-12-04 19:12 UTC, boubou19 commented
what do we do with this PR?

2023-12-04 19:20 UTC, Alastors commented
> what do we do with this PR?

It was rejected, and the CoC was changed to reflect it

2023-12-06 04:24 UTC, Alastors commented
> We discuss it after stable

https://github.com/GTNewHorizons/GTNH-Dev-Doc/blob/master/developer's%20code%20of%20conduct.md 

Dream, respectfully we wasted 2 months on and off discussing this exact topic, please do not waste developer time further on such tripe like this. However, I will remind you of our policies regarding this topic now:

# Code of Conduct 
## Subsection 3: Content Creation
7. Regarding textures within GTNH
7-1. Regarding magic textures: within the vision of the modpack, magic is meant to feel, look, and be different than GregTech, any form of GUI update for the sake of (or that would inadvertently bring) consistency with GT GUIs should be rejected.
7-2. Regarding new textures: try to keep textures consistent with the mod/mod group they're being added to.
7-3. Regarding tooltips: reduction is fine when needed, but if there is a specific consistency, try to stay within that.
7-4. Regarding inventory changing: GUIs that shift the colour of the player's internal inventory are allowed as long as its usage is consistent. Examples being: GT's Steam Machines, Magic Bee's Magic Apiary, Railcraft's Coke Oven, etc.

I cannot stress this further, please do not waste any more of our time on meaningless debate on aesthetic taste, it gets incredibly argumentative, chaotic, downright rude, and quite frankly it's bad for developer moral on the pack. This has already been settled, we need to leave it in the past where it belongs.

Besides, even out of all the debate, no one actually cared for this specific UI, the most anyone actually cared about were the Icons or the rare desire to split the original UI instead.

2023-12-06 09:20 UTC, Connor-Colenso commented
Stating this as a violation of the CoC makes no sense, the mod contains 3 GUIs, 2 of which are vanilla esque, see https://github.com/GTNewHorizons/MagicBees/blob/master/src/main/resources/assets/magicbees/textures/gui/jarScreen.png and https://github.com/GTNewHorizons/MagicBees/blob/master/src/main/resources/assets/magicbees/textures/gui/ringScreen.png and the third is this strange shaded variant.

So arguably this PR actually brings it fully in line with the CoC by giving the same shading to all GUIs?

2023-12-06 13:10 UTC, Caedis commented
The color of the new GUI definitely feels too much like a GT/Vanilla one. I say we keep the old color of the gui, but apply that to all of Magic Bee's guis

2023-12-06 15:59 UTC, Alastors commented
> Stating this as a violation of the CoC makes no sense, the mod contains 3 GUIs, 2 of which are vanilla esque, see https://github.com/GTNewHorizons/MagicBees/blob/master/src/main/resources/assets/magicbees/textures/gui/jarScreen.png and https://github.com/GTNewHorizons/MagicBees/blob/master/src/main/resources/assets/magicbees/textures/gui/ringScreen.png and the third is this strange shaded variant.
> 
> 
> 
> So arguably this PR actually brings it fully in line with the CoC by giving the same shading to all GUIs?

The bee ring and jar one are intentionally clones of each other, also the bee ring is not exactly in optimal shape, frankly I'm not sure if it actually has a recipe but using them as an example of two separate GUIs is very deceptive

2023-12-07 12:04 UTC, Steelux8 commented
The only problem I see here is that a DNA icon doesn't really fit magic content. Other than that, I look at the screenshots and what I think is Forestry bees with a touch of flair and a starry background that makes me think of Astral Sorcery, which *is* a magic mod. It overall looks fine to me, and I didn't really see it as a GT GUI the moment I looked at it.

2023-12-09 22:38 UTC, DrParadox7 commented
> The only problem I see here is that a DNA icon doesn't really fit magic content. Other than that, I look at the screenshots and what I think is Forestry bees with a touch of flair and a starry background that makes me think of Astral Sorcery, which _is_ a magic mod. It overall looks fine to me, and I didn't really see it as a GT GUI the moment I looked at it.

I agree.
This was the original concept for the DNA symbol but I had given up on it as it proved to be too difficult conceptualize it into pixel art (too tiny canvas size and awkward angles):
![image](https://github.com/GTNewHorizons/MagicBees/assets/47131096/bb1ac779-9667-4ffe-ac3d-24e3980d9094)
Feel free to have a go at it

2023-12-13 16:02 UTC, DrParadox7 commented
Made alterations to look less DNA-y and more runic (based on the Inguz rune shown above).
It should be satisfactory enough without compromising clarity.
![image](https://github.com/GTNewHorizons/MagicBees/assets/47131096/e3ce5824-e8f3-4203-82a5-3b96ef9c7ec1)

2024-04-10 04:49 UTC, miaowwwwww commented
tbh, i like the three new texture, how about just keep everything else, only update the 3 pics. i like the brown background and purple linings.

2024-04-11 18:10 UTC, closed without merging